replicaCount: 3

image:
  tag: "latest"
  pullPolicy: "Always"
    
api:
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi
  env:
    # Number of desired Gunicorn workers
    GUNICORN_WORKERS: "1"      

ingress:
  enabled: true
  path: /todoapp
  hosts:
    - localhost
    # TODO to be replaced with your Elastic Load Balancer
    - <replace with your ELB>